entryPoints:
  web:
    address: :80
  web-secure:
    address: :443
    
log:
  filePath: "/var/log/traefik/processStates.log"
  format: "json"

accessLog:
  filePath: "/var/log/traefik/accessLog.log"
  format: json
  fields:
    defaultMode: drop
    names:
      ClientUsername: drop
    headers:
      defaultMode: drop
      names:
        User-Agent: keep # keep user-agent headers
        Authorization: drop
        Content-Type: drop

providers:
  docker:
    endpoint: unix:///var/run/docker.sock
    watch: true
    exposedByDefault: false
    
  file:
    directory: /etc/traefik
    watch: true
    
api:
  dashboard: true
  insecure: true

experimental:
  localPlugins:
    opa2:
      moduleName: github.com/tomn321/opa2
