entryPoints:
  web:
    address: :80
  web-secure:
    address: :443
    
log:
  filePath: "/var/log/traefik/processStates.log"
  format: "json"

accessLog:
  filePath: "/var/log/traefik/accessLog.log"
  format: json
  filters:
    statusCodes:
      - "500"
      - "400-404"
      - "200" # probally best to turn off LOL
    retryAttempts: true
    minDuration: "10ms"
  fields:
    defaultMode: keep
    names:
      ClientUsername: keep
    headers:
      defaultMode: keep
      names:
        User-Agent: keep # keep user-agent headers
        Authorization: keep
        Content-Type: keep

providers:
  docker:
    endpoint: unix:///var/run/docker.sock
    watch: true
    exposedByDefault: false
    
  file:
    directory: /etc/traefik
    watch: true
    
api:
  dashboard: true
  insecure: true

experimental:
  localPlugins:
    opa2:
      moduleName: github.com/tomn321/opa2
